SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE TABLE "public"."chartsoldold" (
  "title"          text    NOT NULL,
  "id"             bigint  GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."charts_id_seq") NOT NULL,
  "difficulty"     text    NOT NULL,
  "level"          text,
  "chart_constant" real,
  "note_count"     integer,
  CONSTRAINT "charts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."chartsoldold"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."charts" (
  "id"              bigint  GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."charts_duplicate_id_seq1") NOT NULL,
  "title"           text,
  "difficulty"      text,
  "level"           text,
  "chart_constant"  real,
  "note_count"      bigint,
  "bpm"             text,
  "length"          text,
  "version"         text,
  "chart_designer"  text,
  "jacket_designer" text,
  "song_id"         text,
  "jacket_override" boolean,
  "artist"          text,
  CONSTRAINT "charts_duplicate_pkey1" PRIMARY KEY (id)
);

ALTER TABLE "public"."charts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."scores" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "chart_id"     bigint,
  "user_id"      uuid                     DEFAULT gen_random_uuid(),
  "score"        bigint,
  "pure"         integer,
  "far"          integer,
  "lost"         integer,
  "created_at"   timestamp with time zone DEFAULT now(),
  "clear_status" text                     NOT NULL,
  CONSTRAINT "scores_pkey" PRIMARY KEY (id),
  CONSTRAINT "unique_user_score" UNIQUE (user_id, chart_id, created_at)
);

ALTER TABLE "public"."scores"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

ALTER TABLE "public"."scores"
  ADD CONSTRAINT "scores_chart_id_fkey" FOREIGN KEY (chart_id) REFERENCES public.charts(id);

CREATE POLICY "Enable read access for all users" ON "public"."charts"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."chartsoldold"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable insert for all users" ON "public"."scores"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."scores"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."charts" TO "anon", "authenticated", "postgres", "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."chartsoldold" TO "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."chartsoldold" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."chartsoldold" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."chartsoldold" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."scores" TO "anon", "authenticated", "postgres", "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

